version: 2
updates:
  # Configuração para npm
  - package-ecosystem: "npm"
    directory: "/meu-portifolio"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
    reviewers:
      - "lucacg" # Substitua pelo seu nome de usuário
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "next"
          - "react*"
        update-types:
          - "minor"
          - "patch"

  # Configuração para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope" 