name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USER }}/portfolio:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USER }}/portfolio:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/${{ secrets.GHCR_USER }}/portfolio:${{ github.sha }}
            docker stop meu-portfolio || true
            docker rm meu-portfolio || true
            docker run -d --name meu-portfolio -p 127.0.0.1:3000:3000 --restart always ghcr.io/${{ secrets.GHCR_USER }}/portfolio:${{ github.sha }}
            sudo nginx -t && sudo systemctl restart nginx
            docker image prune -af